[[solr.misc]]
= Miscellaneous Solr Operation Support

This chapter covers additional support for Solr operations (such as faceting) that cannot be directly accessed via the repository interface. It is recommended to add those operations as custom implementation as described in <<repositories.custom-implementations>> .

[[solr.misc.partialUpdates]]
== Partial Updates

PartialUpdates can be done using `PartialUpdate` which implements `Update`.

====
[source,java]
----
PartialUpdate update = new PartialUpdate("id", "123");
update.add("name", "updated-name");
solrTemplate.saveBean(update);
----
====

[[solr.misc.projection]]
== Projection

Projections can be applied via `@Query` using the fields value.

====
[source,java]
----
@Query(fields = { "name", "id" })
List<ProductBean> findByNameStartingWith(String name);
----
====

[[solr.misc.faceting]]
== Faceting

Faceting cannot be directly applied using the `SolrRepository` but the `SolrTemplate` holds support for this feature.

====
[source,java]
----
FacetQuery query = new SimpleFacetQuery(new Criteria(Criteria.WILDCARD).expression(Criteria.WILDCARD))
  .setFacetOptions(new FacetOptions().addFacetOnField("name").setFacetLimit(5));
FacetPage<Product> page = solrTemplate.queryForFacetPage(query, Product.class);
----
====

Facets on fields and/or queries can also be defined using `@Facet` . Please mind that the result will be a `FacetPage` . NOTE: Using `@Facet` allows you to define place holders which will use your input parameter as value.

====
[source,java]
----
@Query(value = "*:*")
@Facet(fields = { "name" }, limit = 5)
FacetPage<Product> findAllFacetOnName(Pageable page);
----
====

====
[source,java]
----
@Query(value = "popularity:?0")
@Facet(fields = { "name" }, limit = 5, prefix="?1")
FacetPage<Product> findByPopularityFacetOnName(int popularity, String prefix, Pageable page);
----
====

Solr allows definition of facet parameters on a per field basis. In order to add special facet options to defined fields use `FieldWithFacetParameters`.

====
[source,java]
----
// produces: f.name.facet.prefix=spring
FacetOptions options = new FacetOptions();
options.addFacetOnField(new FieldWithFacetParameters("name").setPrefix("spring"));			
----
====

[[solr.misc.faceting.range]]
=== Range Faceting

Range faceting queries may be done by configure required ranges on `FacetOptions`. A simple way to request ranges would be by creating a `FacetOption`, setting this options to a `FacetQuery` and query for a facet page through `SolrTemplate` as follows.  

====
[source,java]
----
FacetOptions facetOptions = new FacetOptions()
  .addFacetByRange(
     new FieldWithNumericRangeParameters("price", 5, 20, 5)
       .setHardEnd(true)
       .setInclude(FacetRangeInclude.ALL)
  )
  .addFacetByRange(
    new FieldWithDateRangeParameters("release", new Date(1420070400), new Date(946684800), "+1YEAR")
      .setInclude(FacetRangeInclude.ALL)
      .setOther(FacetRangeOther.BEFORE)
  );
facetOptions.setFacetMinCount(0);

Criteria criteria = new SimpleStringCriteria("*:*");
SimpleFacetQuery facetQuery = new SimpleFacetQuery(criteria).setFacetOptions(facetOptions);
FacetPage<ExampleSolrBean> statResultPage = solrTemplate.queryForFacetPage(facetQuery, ExampleSolrBean.class);
----
==== 

There are two implementations of fields for facet range requests:

* Numeric Facet Range - used to perform range faceting over numeric fields. To request such range faceting an instance of the class `org.springframework.data.solr.core.query.FacetOptions.FieldWithNumericRangeParameters` can be used. Its instantiation requires a field name, a start value (number), end value (number) and gap (number);
* Date Facet Range - used to perform range faceting over date fields. To request such range faceting an instance of the class `org.springframework.data.solr.core.query.FacetOptions.FieldWithDateRangeParameters` can be used. Its instantiation requires a field name, a start value (date), end value (date) and gap (string). The gap for this kind of field can be defined using `org.apache.solr.util.DateMathParser` (i.e. `+6MONTHS+3DAYS/DAY`, that would mean 6 months and 3 days in the future from now, rounded down to nearest day).

Additionally the following properties can be configured for a field with range parameters (org.springframework.data.solr.core.query.FacetOptions.FieldWithRangeParameters):

* Hard End - `setHardEnd(Boolean)`, defines if the last range should be abruptly ended even if the end doesn't satisfies: `(start - end) % gap = 0`;
* Include - `setInclude(org.apache.solr.common.params.FacetParams.FacetRangeInclude)`, defines how boundaries (lower and upper) shall be handled (exclusive or inclusive) on range facet requests;
* Other - `setOther(org.apache.solr.common.params.FacetParams.FacetRangeOther)`, defines the additional (other) counts for the range facet, i.e. count of documents that are before start of the range facet, end of range facet or even between start and end. 

[[solr.misc.faceting.pivot]]
=== Pivot Faceting

Pivot faceting (Decision Tree) are also supported, and can be queried using `@Facet` annotation as follows: 

====
[source,java]
----
public interface {

	@Facet(pivots = @Pivot({ "category", "dimension" }, pivotMinCount = 0))
	FacetPage<Product> findByTitle(String title, Pageable page);

	@Facet(pivots = @Pivot({ "category", "dimension" }))
	FacetPage<Product> findByDescription(String description, Pageable page);

}
----
====

Alternatively it can be queried using `SolrTemplate` as follows:

====
[source,java]
----
FacetQuery facetQuery = new SimpleFacetQuery(new SimpleStringCriteria("title:foo"));
FacetOptions facetOptions = new FacetOptions();
facetOptions.setFacetMinCount(0);
facetOptions.addFacetOnPivot("category","dimension");
facetQuery.setFacetOptions(facetOptions);
FacetPage<Product> facetResult = solrTemplate.queryForFacetPage(facetQuery, Product.class);
----
==== 

In order to retrieve the pivot results the method `getPivot` can be used as follows:

====
[source,java]
----
List<FacetPivotFieldEntry> pivot = facetResult.getPivot(new SimplePivotField("categories","available"));
----
====

[[solr.misc.terms]]
== Terms

Terms Vector cannot directly be used within `SolrRepository` but can be applied via `SolrTemplate`. Please mind, that the result will be a `TermsPage`.

====
[source,java]
----
TermsQuery query = SimpleTermsQuery.queryBuilder().fields("name").build();
TermsPage page = solrTemplate.queryForTermsPage(query);		
----
====

[[solr.misc.group]]
== Result Grouping / Field Collapsing

Result grouping cannot directly be used within `SolrRepository` but can be applied via `SolrTemplate`. Please mind, that the result will be a `GroupPage`.

====
[source,java]
----
Field field = new SimpleField("popularity");
Function func = ExistsFunction.exists("description");
Query query = new SimpleQuery("inStock:true");

SimpleQuery groupQuery = new SimpleQuery(new SimpleStringCriteria("*:*"));
GroupOptions groupOptions = new GroupOptions()
	.addGroupByField(field)
	.addGroupByFunction(func)
	.addGroupByQuery(query);
groupQuery.setGroupOptions(groupOptions);

GroupPage<Product> page = solrTemplate.queryForGroupPage(query, Product.class);

GroupResult<Product> fieldGroup = page.getGroupResult(field);
GroupResult<Product> funcGroup = page.getGroupResult(func);
GroupResult<Product> queryGroup = page.getGroupResult(query);
----
====

[[solr.misc.fieldStats]]
== Field Stats

Field stats are used to retrieve statistics (max, min, sum, count, mean, missing, stddev and distinct calculations) of given fields from Solr. It is possible by providing `StatsOptions` to your query and reading the `FieldStatsResult` from the returned `StatsPage`. This could be achieved for instance, using `SolrTemplate` as follows:

====
[source,java]
----
// simple field stats
StatsOptions statsOptions = new StatsOptions().addField("price");

// query
SimpleQuery statsQuery = new SimpleQuery("*:*");
statsQuery.setStatsOptions(statsOptions);
StatsPage<Product> statsPage = solrTemplate.queryForStatsPage(statsQuery, Product.class);

// retrieving stats info
FieldStatsResult priceStatResult = statResultPage.getFieldStatsResult("price");
Object max = priceStatResult.getMax();
Long missing = priceStatResult.getMissing();
----
====

The same result could be achieved annotating the repository method with `@Stats` as follows:

====
[source,java]
----
@Query("name:?0")
@Stats(value = { "price" })
StatsPage<Product> findByName(String name, Pageable page);
----
====

Distinct calculation and faceting are also supported:
====
[source,java]
----
// for distinct calculation
StatsOptions statsOptions = new StatsOptions()
    .addField("category")
    // for distinct calculation
    .setCalcDistinct(true)
    // for faceting
    .addFacet("availability");

// query
SimpleQuery statsQuery = new SimpleQuery("*:*");
statsQuery.setStatsOptions(statsOptions);
StatsPage<Product> statsPage = solrTemplate.queryForStatsPage(statsQuery, Product.class);

// field stats
FieldStatsResult categoryStatResult = statResultPage.getFieldStatsResult("category");

// retrieving distinct
List<Object> categoryValues = priceStatResult.getDistinctValues();
Long distinctCount = categoryStatResult.getDistinctCount();

// retrieving faceting
Map<String, StatsResult> availabilityFacetResult = categoryStatResult.getFacetStatsResult("availability");
Long availableCount = availabilityFacetResult.get("true").getCount();
----
====

The annotated version of the sample above would be:
====
[source,java]
----
@Query("name:?0")
@Stats(value = "category", facets = { "availability" }, calcDistinct = true)
StatsPage<Product> findByName(String name);
----
====

In order to perform a selective faceting or selective distinct calculation, `@SelectiveStats` may be used as follows:
====
[source,java]
----
// selective distinct faceting
...
Field facetField = getFacetField();
StatsOptions statsOptions = new StatsOptions()
    .addField("price")
    .addField("category").addSelectiveFacet("name").addSelectiveFacet(facetField);
...
// or annotating repository method as follows
...
@Stats(value = "price", selective = @SelectiveStats(field = "category", facets = { "name", "available" }))
...

// selective distinct calculation
...
StatsOptions statsOptions = new StatsOptions()
    .addField("price")
    .addField("category").setSelectiveCalcDistinct(true);
...
// or annotating repository method as follows
...
@Stats(value = "price", selective = @SelectiveStats(field = "category", calcDistinct = true))
...
----
====

[[solr.misc.filter]]
== Filter Query

Filter Queries improve query speed and do not influence document score. It is recommended to implement geospatial search as filter query. NOTE: Please note that in solr, unless otherwise specified, all units of distance are kilometers and points are in degrees of latitude,longitude.

====
[source,java]
----
Query query = new SimpleQuery(new Criteria("category").is("supercalifragilisticexpialidocious"));
FilterQuery fq = new SimpleFilterQuery(new Criteria("store")
  .near(new Point(48.305478, 14.286699), new Distance(5)));
query.addFilterQuery(fq);
----
====

Simple filter queries can also be defined using `@Query` . NOTE: Using `@Query` allows you to define place holders which will use your input parameter as value.

====
[source,java]
----
@Query(value = "*:*", filters = { "inStock:true", "popularity:[* TO 3]" })
List<Product> findAllFilterAvailableTrueAndPopularityLessThanEqual3();
----
====

[[solr.misc.timeAllowed]]
== Time allowed for a search

It it possible to set the time allowed for a search to finish. This value only applies to the search and not to requests in general. Time is in milliseconds. Values less than or equal to zero implies no time restriction. Partial results may be returned, if there are any.

====
[source,java]
----
Query query = new SimpleQuery(new SimpleStringCriteria("field_1:value_1"));
// Allowing maximum of 100ms for this search
query.setTimeAllowed(100);
----
====

[[solr.misc.boost]]
== Boost document Score

Boost document score in case of matching criteria to influence result order. This can be done by either setting boost on `Criteria` or using `@Boost` for derived queries.

====
[source,java]
----
Page<Product> findByNameOrDescription(@Boost(2) String name, String description);
----
====

[[solr.misc.boost.index-time]]
=== Index Time Boosts

Boosting documents score can be done on index time by using `@SolrDocument` annotation on classes (for Solr documents) and/or `@Indexed` on fields (for Solr fields).

====
[source,java]
----
import org.apache.solr.client.solrj.beans.Field;
import org.springframework.data.solr.repository.Boost;

@SolrDocument(boost = 0.8f)
public class MyEntity {

    @Id
    @Indexed
    private String id;
    
    @Indexed(boost = 1.0f)
    private String name;
    
    // setters and getters ...

}	            
----
====

[[solr.misc.requesthandler]]
== Select Request Handler

Select the request handler via `qt` Parameter directly in `Query` or add `@Query` to your method signature.

====
[source,java]
----
@Query(requestHandler = "/instock")
Page<Product> findByNameOrDescription(String name, String description);
----
====

[[solr.misc.join]]
== Using Join

Join attributes within one solr core by defining `Join` attribute of `Query`. NOTE: Join is not available prior to solr 4.x.

====
[source,java]
----
SimpleQuery query = new SimpleQuery(new SimpleStringCriteria("text:ipod"));
query.setJoin(Join.from("manu_id_s").to("id"));
----
====

[[solr.misc.highlighting]]
== Highlighting

To highlight matches in search result add `HighlightOptions` to the `SimpleHighlightQuery`. Providing `HighlightOptions` without any further attributes will highlight apply highlighting on all fields within a `SolrDocument`.  NOTE: Field specific highlight parameters can be set by adding `FieldWithHighlightParameters` to `HighlightOptions`.

====
[source,java]
----
SimpleHighlightQuery query = new SimpleHighlightQuery(new SimpleStringCriteria("name:with"));
query.setHighlightOptions(new HighlightOptions());
HighlightPage<Product> page = solrTemplate.queryForHighlightPage(query, Product.class);
----
====

Not all parameters are available via setters/getters but can be added directly.

====
[source,java]
----
SimpleHighlightQuery query = new SimpleHighlightQuery(new SimpleStringCriteria("name:with"));
query.setHighlightOptions(new HighlightOptions().addHighlightParameter("hl.bs.country", "at"));
----
====

In order to apply Highlighting to derived queries use `@Highlight`. If no `fields` are defined highlighting will be aplied on all fields.

====
[source,java]
----
@Highlight(prefix = "<b>", postfix = "</b>")
HighlightPage<Product> findByName(String name, Pageable page);
----
====

[[solr.misc.spellcheck]]
== Spellchecking

Spellchecking offers search term suggestions based on the actual query. Please see the https://cwiki.apache.org/confluence/display/solr/Spell+Checking[Solr Reference] for more details.

=== Spellecheck Options

Spellcheck query parameters are added to request when `SpellcheckOptions` are set.

====
[source,java]
----
SimpleQuery q = new SimpleQuery("name:gren");
q.setSpellcheckOptions(SpellcheckOptions.spellcheck()               <1>
  .dictionaries("dict1", "dict2")                                   <2>
  .count(5)                                                         <3>
  .extendedResults());                                              <4>
q.setRequestHandler("/spell");                                      <5>

SpellcheckedPage<Product> found = template.query(q, Product.class); <6>
----
<1> Enable spellcheck by setting `SpellcheckOptions`. Sets `spellcheck=on` request parameter.
<2> Set up the dictionaries to use for lookup.
<3> Set the max number of suggestions to return.
<4> Enable extended results including term frequency etc.
<5> Set the request handler capable of processing suggestions.
<6> Execute the query.
====

=== @Spellcheck

The `@Spellcheck` annotations allows usage of the spellcheck feature on `Repository` level.

====
[source,java]
----
public interface ProductRepository extends Repository<Product, String> {

  @Query(requestHandler = "/spell")
  @Spellcheck(dictionaries = { "dict1", "dic2" }, count=5, extendedResults = true)
  SpellcheckedPage<Product> findByName(String name, Pageable page);

}
----
====

[[solr.misc.functions]]
== Using Functions

Solr supports several functional expressions within queries. Followig functions are supported out of the box. Custom functions can be added by implementing `Function` 

[cols="1,2", options="header"]
.Functions
|===
| Class
| Solr Function| `CurrencyFunction`
| `currency(field_name,[CODE])`

| `DefaultValueFunction`
| `def(field\|function,defaultValue)`

| `DistanceFunction`
| `dist(power, pointA, pointB)`

| `DivideFunction`
| `div(x,y)`

| `ExistsFunction`
| `exists(field\|function)`

| `GeoDistanceFunction`
| `geodist(sfield, latitude, longitude)`

| `GeoHashFunction`
| `geohash(latitude, longitude)`

| `IfFunction`
| `if(value\|field\|function,trueValue,falseValue)`

| `MaxFunction`
| `max(field\|function,value)`

| `NotFunction`
| `not(field\|function)`

| `ProductFunction`
| `product(x,y,...)`

| `QueryFunction`
| `query(x)`

| `TermFrequencyFunction`
| `termfreq(field,term)`
|===

====
[source,java]
----
SimpleQuery query = new SimpleQuery(new SimpleStringCriteria("text:ipod"));
query.addFilterQuery(new FilterQuery(Criteria.where(QueryFunction.query("name:sol*"))));
----
====

[[solr.misc.realtimeGet]]
== Realtime Get

The realtime get allows retrieval of the latest version of any document using the unique-key, without the need to reopen searchers.

NOTE: realtime get relies on the update log feature.

.Realtime get
====
[source,java]
----
Product product = solrTemplate.getById("123", Product.class);
----
====

Multiple documents can be retrieved by providing a collection of ids as follows:

.Realtime multi-get
====
[source,java]
----
Collection<String> ids = Arrays.asList("123", "134");
Collection<Product> products = solrTemplate.getById(ids, Product.class);
----
====

[[solr.misc.specialFields]]
== Special Fields

=== @Score

In order to load score information of a query result, a field annotated with `@Score` annotation could be added, indicating the property holding the documents score.

NOTE: The score property needs to be numerical and can only appear once per document.

====
[source,java]
----
public class MyEntity {

    @Id
    private String id;
    
    @Score
    private Float score;
    
    // setters and getters ...

}	            
----
====